# Auto-generated by luavsg top-level CMakeLists.txt
# Prefer vendored zlib targets over filesystem probing.

if(TARGET zlibstatic)
  if(NOT TARGET ZLIB::ZLIB)
    add_library(ZLIB::ZLIB ALIAS zlibstatic)
  endif()
  set(ZLIB_FOUND TRUE)
  set(ZLIB_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/lib/zlib")
  set(ZLIB_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/lib/zlib")
  return()
endif()

if(TARGET zlib)
  if(NOT TARGET ZLIB::ZLIB)
    add_library(ZLIB::ZLIB ALIAS zlib)
  endif()
  set(ZLIB_FOUND TRUE)
  set(ZLIB_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/lib/zlib")
  set(ZLIB_INCLUDE_DIRS "${CMAKE_SOURCE_DIR}/lib/zlib")
  return()
endif()

# Fall back: let the caller handle absence (or provide ZLIB_ROOT/ZLIB_LIBRARY).
set(ZLIB_FOUND FALSE)
